config/routes.rb
require 'sidekiq/web'

class CookiesConstraint
  def self.matches?(request)
    request.cookie_jar.signed['identity_id'] || request.cookie_jar.signed['remember_identity_id']
  end
end

Rails.application.routes.draw do
  root 'dashboard#show', constraints: CookiesConstraint
  root 'marketing#show'

  resource :dashboard, only: %i(show), controller: 'dashboard'
  resource :registration, only: %i(new create)
  resource :session, only: %i(new create destroy)

  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: '/graphiql', graphql_path: '/graphql'
  end

  post '/graphql', to: 'graphql#execute'

  mount Sidekiq::Web => '/sidekiq'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ticker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'style', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= tag.div do %>
      <%= tag.section class: 'root' do %>
        <%= tag.header class: 'shadow-small' do %>
          <%= tag.div class: 'large-container border-box clearfix px3' do %>
            <%= tag.div class: 'flex flex-justify-content' do %>
              <%= tag.div do %>
                <%= tag.span class: 'logo-container', data: { height: 28, width: 28 } %>
                <%= link_to root_path, class: 'h5 align-middle inline-block no-underline-on-hover black blue-on-hover logo-text', title: 'Ticker home' do %>
                  <%= tag.p class: 'mb0 mt0 align-middle sm-show nowrap' do %>
                    <%= tag.b 'Ticker' %>
                    <%= tag.span 'Beta', class: 'h6' %>
                  <% end %>
                <% end %>
              <% end %>

              <%= tag.div do %>
                <% if current_account %>
                  <%= link_to session_path, method: :delete, class: 'mb0 nowrap black bold blue-on-hover border-box no-underline-on-hover nav-btn--account js-account-button' do %>
                    <%= tag.div do %>
                      <%= tag.p 'Log out', class: 'h5 align-middle inline-block no-underline-on-hover black blue-on-hover mt0', style: 'margin-top: 20px;', title: "Log out" %>
                    <% end %>
                  <% end %>
                <% end %>

                <% unless current_account %>
                  <%= link_to new_session_path, class: 'mb0 nowrap black bold blue-on-hover border-box no-underline-on-hover nav-btn--account js-account-button' do %>
                    <%= tag.div do %>
                      <%= tag.p 'Log in', class: 'h5 align-middle inline-block no-underline-on-hover black blue-on-hover mt0', style: 'margin-top: 20px;' %>
                    <% end %>
                  <% end %>
                <% end %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>

        <%= yield %>
      <% end %>
    <% end %>

    <%= render partial: 'shared/intercom' %>
  </body>
</html>

<%= javascript_pack_tag 'logo' %>

app/views/layouts/authentication.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ticker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'style', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= tag.div do %>
      <%= tag.section class: 'large-container small-container md-p3 border-box table col-12 height-100vh' do %>
        <%= yield %>
      <% end %>
    <% end %>

    <%= render partial: 'shared/intercom' %>
  </body>
</html>

<%= javascript_pack_tag 'logo' %>